# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9cd6f4f867581175a524190ddf821abf3d8339d394354863c1f4a1ea219ae37a33f0fe62070fba9dcf6df896ac1b6006135f7e38f71964a057b69a4d307504af

test:
  secret_key_base: 68854da2f007e33288add2867a9bcb164c95f65694b786e37b19d7017e96650cc83f5d352605b5e094802f8a6c4920ab79c6a4b59265b9e44a44bf3fc117d63b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
